#!/bin/sh

start() {
    if command -v ifconfig >/dev/null 2>&1; then
        ifconfig lo 127.0.0.1 netmask 255.0.0.0 up
    else
        busybox ifconfig lo 127.0.0.1 netmask 255.0.0.0 up
    fi
}

stop() {
    :
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; start ;;
    *) echo "Usage: $0 {start|stop|restart}"; exit 1 ;;
esac

exit 0
