up=keyboard,273,SDLK_UP
down=keyboard,274,SDLK_DOWN
left=keyboard,276,SDLK_LEFT
right=keyboard,275,SDLK_RIGHT
confirm=keyboard,97,SDLK_a
cancel=keyboard,98,SDLK_b
menu=keyboard,13,SDLK_RETURN
settings=keyboard,9,SDLK_TAB
manual=keyboard,120,SDLK_x
modifier=keyboard,121,SDLK_y
section_prev=keyboard,280,SDLK_PAGEUP
section_next=keyboard,281,SDLK_PAGEDOWN
pageup=keyboard,280,SDLK_PAGEUP
pagedown=keyboard,281,SDLK_PAGEDOWN
voldown=keyboard,278,SDLK_HOME
volup=keyboard,279,SDLK_END
dec=keyboard,121,SDLK_y
inc=keyboard,120,SDLK_x
