--- drivers/staging/Makefile
+++ drivers/staging/Makefile
@@ -53,3 +53,5 @@
 obj-$(CONFIG_USB_WUSB)		+= wusbcore/
 obj-$(CONFIG_EXFAT_FS)		+= exfat/
 obj-$(CONFIG_QLGE)		+= qlge/
+obj-$(CONFIG_PRISM2_USB)	+= wlan-ng/
+obj-$(CONFIG_SHIROGANE)		+= shirogane/
